import type { Metadata } from "next";
import { Syne, Inter, Chivo } from "next/font/google";
import "./globals.css";

const syne = Syne({
  subsets: ["latin"],
  variable: '--font-syne',
});

const inter = Inter({
  subsets: ["latin"],
  variable: '--font-inter',
});

const chivo = Chivo({
  subsets: ["latin"],
  variable: '--font-chivo',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${syne.variable} ${inter.variable} ${chivo.variable}`}>
      <body className='antialiased'>
        {children}
      </body>
    </html>
  );
}
